import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import Papa from "papaparse";
import {
  BarChart3, BookOpen, CalendarDays, Check, ChevronRight, Clock3, Download, FileJson,
  GraduationCap, Home, Languages, ListTodo, Menu, Monitor, Moon, MoreHorizontal,
  Plus, RotateCcw, Settings, Sun, Target, Timer, Trash2, Upload, X,
} from "lucide-react";

type View = "home" | "schedule" | "tasks" | "stats";
type Theme = "light" | "dark" | "system";
type Locale = "zh" | "ja" | "en";
type TaskType = "assignment" | "report" | "exam" | "preview" | "review" | "general";
type Priority = "low" | "medium" | "high";
type Subtask = { id: string; title: string; completed: boolean };
type CourseSchedule = { id: string; weekday: number; startTime: string; endTime: string; room?: string };
type Course = { id: string; name: string; teacher: string; room: string; color: string; credits: number; notes: string; schedule: CourseSchedule[]; createdAt: number };
type StudyTask = { id: string; title: string; courseId?: string; type: TaskType; dueAt?: string; priority: Priority; tags: string[]; subtasks: Subtask[]; notes: string; repeat: "none" | "daily" | "weekly" | "monthly"; completed: boolean; completedAt?: number; isDailyFocus: boolean; createdAt: number; updatedAt: number };
type FocusSession = { id: string; courseId?: string; taskId?: string; startedAt: number; durationMinutes: number };
type AppData = { schemaVersion: 3; courses: Course[]; tasks: StudyTask[]; focusSessions: FocusSession[] };

const DATA_KEY = "student-focus-data-v3";
const OLD_KEY = "todo-apple-tasks-v2";
const BACKUP_KEY = "todo-apple-pre-v3-backup";
const THEME_KEY = "todo-apple-theme";
const LOCALE_KEY = "todo-apple-locale";
const ICON_KEY = "todo-apple-custom-icon";
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const iso = (days: number, hour = 23) => { const d = new Date(); d.setDate(d.getDate() + days); d.setHours(hour, 0, 0, 0); return d.toISOString().slice(0, 16); };

const copy = {
  zh: { home:"首页", schedule:"课表", tasks:"任务", stats:"统计", settings:"设置", today:"今日学习", subtitle:"课程、截止事项与专注进度", courses:"今日课程", pending:"待完成", overdue:"已逾期", next:"下一节课", weekly:"本周要交什么", exams:"最近考试", focus3:"今日三件事", addTask:"新建任务", addCourse:"添加课程", empty:"暂无事项", teacher:"教师", room:"教室", credits:"学分", details:"课程详情", assignment:"作业", report:"报告", exam:"考试", preview:"预习", review:"复习", general:"普通事项", all:"全部", incomplete:"未完成", completed:"已完成", high:"高", medium:"中", low:"低", due:"截止时间", course:"课程", type:"类型", priority:"优先级", tags:"标签", notes:"备注", repeat:"重复", title:"标题", save:"保存", cancel:"取消", monday:"周一", tuesday:"周二", wednesday:"周三", thursday:"周四", friday:"周五", saturday:"周六", sunday:"周日", completion:"本周完成率", distribution:"任务类型分布", trend:"近 7 天完成", focusTime:"专注时长", streak:"连续完成", days:"天", minutes:"分钟", backup:"完整备份", restore:"恢复备份", importCsv:"导入 CSV", exportCsv:"导出 CSV", language:"语言", appearance:"外观", light:"浅色", dark:"深色", system:"跟随系统", icon:"自定义图标", overdueLabel:"已逾期", urgent:"24 小时内", data:"数据管理" },
  ja: { home:"ホーム", schedule:"時間割", tasks:"タスク", stats:"統計", settings:"設定", today:"今日の学習", subtitle:"授業、締切、集中の進捗", courses:"今日の授業", pending:"未完了", overdue:"期限切れ", next:"次の授業", weekly:"今週の締切", exams:"試験予定", focus3:"今日の3つ", addTask:"タスク追加", addCourse:"授業追加", empty:"予定なし", teacher:"担当", room:"教室", credits:"単位", details:"授業詳細", assignment:"課題", report:"レポート", exam:"試験", preview:"予習", review:"復習", general:"その他", all:"すべて", incomplete:"未完了", completed:"完了", high:"高", medium:"中", low:"低", due:"期限", course:"授業", type:"種類", priority:"優先度", tags:"タグ", notes:"メモ", repeat:"繰り返し", title:"タイトル", save:"保存", cancel:"キャンセル", monday:"月", tuesday:"火", wednesday:"水", thursday:"木", friday:"金", saturday:"土", sunday:"日", completion:"今週の完了率", distribution:"種類別", trend:"7日間の完了", focusTime:"集中時間", streak:"連続達成", days:"日", minutes:"分", backup:"完全バックアップ", restore:"復元", importCsv:"CSV読込", exportCsv:"CSV書出", language:"言語", appearance:"表示", light:"ライト", dark:"ダーク", system:"システム", icon:"アイコン", overdueLabel:"期限切れ", urgent:"24時間以内", data:"データ管理" },
  en: { home:"Home", schedule:"Schedule", tasks:"Tasks", stats:"Insights", settings:"Settings", today:"Today's study", subtitle:"Classes, deadlines and focus progress", courses:"Classes today", pending:"To do", overdue:"Overdue", next:"Next class", weekly:"Due this week", exams:"Upcoming exams", focus3:"Today's three", addTask:"New task", addCourse:"Add course", empty:"Nothing scheduled", teacher:"Teacher", room:"Room", credits:"Credits", details:"Course details", assignment:"Assignment", report:"Report", exam:"Exam", preview:"Preview", review:"Review", general:"General", all:"All", incomplete:"Incomplete", completed:"Completed", high:"High", medium:"Medium", low:"Low", due:"Due", course:"Course", type:"Type", priority:"Priority", tags:"Tags", notes:"Notes", repeat:"Repeat", title:"Title", save:"Save", cancel:"Cancel", monday:"Mon", tuesday:"Tue", wednesday:"Wed", thursday:"Thu", friday:"Fri", saturday:"Sat", sunday:"Sun", completion:"Weekly completion", distribution:"Task mix", trend:"7-day trend", focusTime:"Focus time", streak:"Streak", days:"days", minutes:"min", backup:"Full backup", restore:"Restore", importCsv:"Import CSV", exportCsv:"Export CSV", language:"Language", appearance:"Appearance", light:"Light", dark:"Dark", system:"System", icon:"Custom icon", overdueLabel:"Overdue", urgent:"Due in 24h", data:"Data" },
};

const seed = (): AppData => {
  const c1 = uid(), c2 = uid(), c3 = uid();
  return { schemaVersion:3, courses:[
    { id:c1,name:"数据结构",teacher:"陈老师",room:"理科楼 302",color:"#2878e3",credits:4,notes:"",createdAt:Date.now(),schedule:[{id:uid(),weekday:1,startTime:"09:00",endTime:"10:30",room:"理科楼 302"},{id:uid(),weekday:4,startTime:"09:00",endTime:"10:30",room:"理科楼 302"}] },
    { id:c2,name:"学术英语",teacher:"田中老师",room:"文科楼 205",color:"#16a085",credits:2,notes:"",createdAt:Date.now(),schedule:[{id:uid(),weekday:2,startTime:"13:00",endTime:"14:30",room:"文科楼 205"}] },
    { id:c3,name:"微观经济学",teacher:"李老师",room:"经管楼 108",color:"#8854d0",credits:3,notes:"",createdAt:Date.now(),schedule:[{id:uid(),weekday:3,startTime:"10:45",endTime:"12:15",room:"经管楼 108"}] },
  ], tasks:[
    {id:uid(),title:"完成链表实验",courseId:c1,type:"assignment",dueAt:iso(1,18),priority:"high",tags:["实验"],subtasks:[],notes:"",repeat:"none",completed:false,isDailyFocus:true,createdAt:Date.now(),updatedAt:Date.now()},
    {id:uid(),title:"阅读 Chapter 6",courseId:c2,type:"preview",dueAt:iso(3),priority:"medium",tags:[],subtasks:[],notes:"",repeat:"none",completed:false,isDailyFocus:true,createdAt:Date.now(),updatedAt:Date.now()},
    {id:uid(),title:"期中考试",courseId:c3,type:"exam",dueAt:iso(12,10),priority:"high",tags:[],subtasks:[],notes:"闭卷",repeat:"none",completed:false,isDailyFocus:false,createdAt:Date.now(),updatedAt:Date.now()},
  ], focusSessions:[{id:uid(),courseId:c1,startedAt:Date.now()-86400000,durationMinutes:45}] };
};

function loadData(): AppData {
  try { const current=localStorage.getItem(DATA_KEY); if(current) return JSON.parse(current); const old=localStorage.getItem(OLD_KEY); if(!old) return seed(); localStorage.setItem(BACKUP_KEY,old); const oldTasks=JSON.parse(old); return {schemaVersion:3,courses:[],focusSessions:[],tasks:oldTasks.map((x:any)=>({id:x.id||uid(),title:x.title,courseId:undefined,type:"general",dueAt:x.dueDate?`${x.dueDate}T23:59`:undefined,priority:"medium",tags:x.tags||[],subtasks:x.subtasks||[],notes:"",repeat:x.repeat||"none",completed:!!x.completed,completedAt:x.completed?Date.now():undefined,isDailyFocus:false,createdAt:x.createdAt||Date.now(),updatedAt:Date.now()}))}; } catch { return seed(); }
}

const dayKeys=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
const typeKeys:TaskType[]=["assignment","report","exam","preview","review","general"];

export default function App(){
  const [data,setData]=useState<AppData>(loadData); const [view,setView]=useState<View>("home");
  const [theme,setTheme]=useState<Theme>(()=>(localStorage.getItem(THEME_KEY) as Theme)||"system"); const [locale,setLocale]=useState<Locale>(()=>(localStorage.getItem(LOCALE_KEY) as Locale)||"zh");
  const [settings,setSettings]=useState(false); const [taskForm,setTaskForm]=useState(false); const [courseForm,setCourseForm]=useState(false); const [selectedCourse,setSelectedCourse]=useState<string>(); const [filter,setFilter]=useState("all");
  const [customIcon,setCustomIcon]=useState(()=>localStorage.getItem(ICON_KEY)||""); const fileRef=useRef<HTMLInputElement>(null); const jsonRef=useRef<HTMLInputElement>(null); const iconRef=useRef<HTMLInputElement>(null);
  const t=copy[locale]; const now=new Date(); const weekday=now.getDay()||7;
  useEffect(()=>localStorage.setItem(DATA_KEY,JSON.stringify(data)),[data]); useEffect(()=>localStorage.setItem(LOCALE_KEY,locale),[locale]);
  useEffect(()=>{const m=matchMedia("(prefers-color-scheme:dark)");const apply=()=>document.documentElement.classList.toggle("dark",theme==="dark"||(theme==="system"&&m.matches));apply();localStorage.setItem(THEME_KEY,theme);m.addEventListener("change",apply);return()=>m.removeEventListener("change",apply)},[theme]);
  const courseMap=useMemo(()=>Object.fromEntries(data.courses.map(c=>[c.id,c])),[data.courses]);
  const pending=data.tasks.filter(x=>!x.completed), overdue=pending.filter(x=>x.dueAt&&new Date(x.dueAt)<now), todayCourses=data.courses.filter(c=>c.schedule.some(s=>s.weekday===weekday));
  const dueWeek=pending.filter(x=>x.dueAt&&new Date(x.dueAt).getTime()<Date.now()+7*86400000).sort((a,b)=>String(a.dueAt).localeCompare(String(b.dueAt)));
  const exams=pending.filter(x=>x.type==="exam"&&x.dueAt).sort((a,b)=>String(a.dueAt).localeCompare(String(b.dueAt))).slice(0,4); const focus3=data.tasks.filter(x=>x.isDailyFocus).slice(0,3);
  const nextClass=useMemo(()=>{const options=todayCourses.flatMap(c=>c.schedule.filter(s=>s.weekday===weekday).map(s=>({c,s}))).sort((a,b)=>a.s.startTime.localeCompare(b.s.startTime));return options.find(x=>x.s.endTime>now.toTimeString().slice(0,5))||options[0]},[data.courses,weekday]);
  const completion=data.tasks.length?Math.round(data.tasks.filter(x=>x.completed).length/data.tasks.length*100):0;
  const toggle=(id:string)=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,completed:!x.completed,completedAt:!x.completed?Date.now():undefined,updatedAt:Date.now()}:x)}));
  const setFocus=(id:string)=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,isDailyFocus:!x.isDailyFocus}:x)}));
  const addTask=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const task:StudyTask={id:uid(),title:String(f.get("title")),courseId:String(f.get("course")||"")||undefined,type:f.get("type") as TaskType,dueAt:String(f.get("due")||"")||undefined,priority:f.get("priority") as Priority,tags:String(f.get("tags")||"").split(",").filter(Boolean),subtasks:[],notes:String(f.get("notes")||""),repeat:"none",completed:false,isDailyFocus:false,createdAt:Date.now(),updatedAt:Date.now()};setData(d=>({...d,tasks:[task,...d.tasks]}));setTaskForm(false)};
  const addCourse=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const c:Course={id:uid(),name:String(f.get("name")),teacher:String(f.get("teacher")),room:String(f.get("room")),color:String(f.get("color")),credits:Number(f.get("credits")),notes:String(f.get("notes")),createdAt:Date.now(),schedule:[{id:uid(),weekday:Number(f.get("weekday")),startTime:String(f.get("start")),endTime:String(f.get("end")),room:String(f.get("room"))}]};setData(d=>({...d,courses:[...d.courses,c]}));setCourseForm(false)};
  const exportJson=()=>download("student-focus-backup.json",JSON.stringify(data,null,2),"application/json"); const exportCsv=()=>download("student-tasks.csv",Papa.unparse(data.tasks.map(x=>({...x,tags:x.tags.join("|"),subtasks:JSON.stringify(x.subtasks)}))),"text/csv");
  const importJson=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(x.schemaVersion===3&&Array.isArray(x.tasks))setData(x)}catch{}};r.readAsText(f)};
  const importCsv=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;Papa.parse<any>(f,{header:true,complete:({data:rows})=>setData(d=>({...d,tasks:[...rows.filter((r:any)=>r.title).map((r:any)=>({...r,id:r.id||uid(),completed:r.completed==="true",tags:String(r.tags||"").split("|").filter(Boolean),subtasks:[],createdAt:Number(r.createdAt)||Date.now(),updatedAt:Date.now()})),...d.tasks]}))})};
  const updateIcon=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const v=String(r.result);setCustomIcon(v);localStorage.setItem(ICON_KEY,v)};r.readAsDataURL(f)};
  function download(name:string,body:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",body],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

  return <div className="app-shell"><div className="student-app">
    <aside className="sidebar panel"><Brand icon={customIcon}/><Nav view={view} setView={setView} t={t}/><div className="course-nav"><div><span>{t.course}</span><button onClick={()=>setCourseForm(true)} aria-label={t.addCourse}><Plus/></button></div>{data.courses.map(c=><button key={c.id} onClick={()=>{setSelectedCourse(c.id);setView("schedule")}}><i style={{background:c.color}}/>{c.name}</button>)}</div><button className="settings-link" onClick={()=>setSettings(true)}><Settings/>{t.settings}</button></aside>
    <header className="mobile-header glass-lite"><Brand icon={customIcon}/><button onClick={()=>setSettings(true)} aria-label={t.settings}><Settings/></button></header>
    <main className="workspace">
      {view==="home"&&<HomeView {...{t,data,todayCourses,pending,overdue,nextClass,dueWeek,exams,focus3,courseMap,toggle,setFocus,setTaskForm,completion}}/>}
      {view==="schedule"&&<ScheduleView {...{t,data,weekday,selectedCourse,setSelectedCourse,setTaskForm,setCourseForm,courseMap}}/>}
      {view==="tasks"&&<TasksView {...{t,data,courseMap,filter,setFilter,toggle,setFocus,setTaskForm,setData}}/>}
      {view==="stats"&&<StatsView {...{t,data,courseMap,completion}}/>}
    </main>
    <nav className="mobile-nav glass-lite"><Nav view={view} setView={setView} t={t}/></nav>
    {settings&&<SettingsPanel {...{t,theme,setTheme,locale,setLocale,setSettings,customIcon,fileRef,jsonRef,iconRef,exportCsv,exportJson,importCsv,importJson,updateIcon}}/>}
    {taskForm && <TaskDrawer t={t} courses={data.courses} addTask={addTask} close={() => setTaskForm(false)} defaultCourse={selectedCourse} />}
    {courseForm && <CourseDrawer t={t} addCourse={addCourse} close={() => setCourseForm(false)} />}
  </div></div>
}

function Brand({icon}:{icon:string}){return <div className="brand"><div className="brand-mark">{icon?<img src={icon} alt=""/>:<GraduationCap/>}</div><div><strong>StudyFlow</strong><span>Student workspace</span></div></div>}
function Nav({view,setView,t}:{view:View;setView:(v:View)=>void;t:any}){const items:[View,any,any][]=[["home",Home,t.home],["schedule",CalendarDays,t.schedule],["tasks",ListTodo,t.tasks],["stats",BarChart3,t.stats]];return <div className="nav-list">{items.map(([v,I,label])=><button className={view===v?"active":""} onClick={()=>setView(v)} key={v}><I/><span>{label}</span></button>)}</div>}
function SectionTitle({title,action}:{title:string;action?:ReactNode}){return <div className="section-title"><h2>{title}</h2>{action}</div>}
function HomeView(p:any){const {t,data,todayCourses,pending,overdue,nextClass,dueWeek,exams,focus3,courseMap,toggle,setFocus,setTaskForm,completion}=p;return <><div className="page-head"><div><span>{new Intl.DateTimeFormat(undefined,{month:"long",day:"numeric",weekday:"long"}).format(new Date())}</span><h1>{t.today}</h1><p>{t.subtitle}</p></div><button className="primary" onClick={()=>setTaskForm(true)}><Plus/>{t.addTask}</button></div><div className="desktop-grid"><div className="main-column"><div className="overview-grid"><Metric label={t.courses} value={todayCourses.length} icon={BookOpen}/><Metric label={t.pending} value={pending.length} icon={ListTodo}/><Metric label={t.overdue} value={overdue.length} icon={Clock3} danger={overdue.length>0}/></div><section className="entity-card next-class"><SectionTitle title={t.next}/>{nextClass?<div><i style={{background:nextClass.c.color}}/><div><h3>{nextClass.c.name}</h3><p>{nextClass.s.startTime}–{nextClass.s.endTime} · {nextClass.s.room}</p><span>{nextClass.c.teacher}</span></div></div>:<Empty t={t}/>}</section><section><SectionTitle title={t.weekly} action={<button className="text-button" onClick={()=>setTaskForm(true)}><Plus/>{t.addTask}</button>}/><div className="deadline-list">{dueWeek.length?dueWeek.map((x:any)=><TaskRow key={x.id} task={x} course={courseMap[x.courseId]} t={t} toggle={toggle} setFocus={setFocus}/>):<Empty t={t}/>}</div></section></div><aside className="right-column"><section className="entity-card"><SectionTitle title={t.exams}/>{exams.length?exams.map((x:any)=><ExamRow key={x.id} task={x} course={courseMap[x.courseId]} t={t}/>):<Empty t={t}/>}</section><section className="entity-card"><SectionTitle title={t.focus3} action={<span className="progress-label">{focus3.filter((x:any)=>x.completed).length}/3</span>}/><div className="focus-list">{focus3.map((x:any)=><label key={x.id}><button className={x.completed?"done":""} onClick={()=>toggle(x.id)}><Check/></button><span>{x.title}</span><button onClick={()=>setFocus(x.id)}><X/></button></label>)}{focus3.length<3&&<p>{3-focus3.length} slots available</p>}</div><div className="mini-progress"><i style={{width:`${focus3.length?focus3.filter((x:any)=>x.completed).length/focus3.length*100:0}%`}}/></div></section><section className="entity-card summary"><span>{t.completion}</span><strong>{completion}%</strong><div className="mini-progress"><i style={{width:`${completion}%`}}/></div></section></aside></div></>}
function Metric({label,value,icon:Icon,danger}:{label:string;value:number;icon:any;danger?:boolean}){return <div className={`metric entity-card ${danger?"danger":""}`}><Icon/><div><strong>{value}</strong><span>{label}</span></div></div>}
function TaskRow({task,course,t,toggle,setFocus}:{task:StudyTask;course?:Course;t:any;toggle:(x:string)=>void;setFocus:(x:string)=>void}){const due=task.dueAt?new Date(task.dueAt):null;const diff=due?due.getTime()-Date.now():0;return <article className={`task-row-card entity-card ${diff<0?"overdue":diff<86400000?"urgent":""}`}><button className={`task-check ${task.completed?"done":""}`} onClick={()=>toggle(task.id)}><Check/></button><div><h3>{task.title}</h3><p>{course?.name||t.general} · {t[task.type]}</p></div><div className="task-due"><span>{due?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(due):"—"}</span>{diff<0&&<b>{t.overdueLabel}</b>}{diff>=0&&diff<86400000&&<b>{t.urgent}</b>}</div><button className={`focus-star ${task.isDailyFocus?"active":""}`} onClick={()=>setFocus(task.id)}><Target/></button></article>}
function ExamRow({task,course,t}:{task:StudyTask;course?:Course;t:any}){const days=Math.max(0,Math.ceil((new Date(task.dueAt!).getTime()-Date.now())/86400000));return <div className="exam-row"><div><strong>{task.title}</strong><span>{course?.name||t.general}</span></div><b>{days}<small>{t.days}</small></b></div>}
function ScheduleView({t,data,weekday,selectedCourse,setSelectedCourse,setTaskForm,setCourseForm,courseMap}:any){if(selectedCourse){const c=courseMap[selectedCourse];const tasks=data.tasks.filter((x:any)=>x.courseId===c.id);return <><div className="page-head"><div><button className="back" onClick={()=>setSelectedCourse(undefined)}>‹ {t.schedule}</button><h1>{c.name}</h1><p>{c.teacher} · {c.room} · {c.credits} {t.credits}</p></div><button className="primary" onClick={()=>setTaskForm(true)}><Plus/>{t.addTask}</button></div><div className="course-detail"><section className="entity-card course-profile"><i style={{background:c.color}}/><h2>{c.name}</h2><p>{c.notes||t.empty}</p><strong>{tasks.length?Math.round(tasks.filter((x:any)=>x.completed).length/tasks.length*100):0}%</strong></section><section><SectionTitle title={t.tasks}/><div className="deadline-list">{tasks.map((x:any)=><TaskRow key={x.id} task={x} course={c} t={t} toggle={()=>{}} setFocus={()=>{}}/>)}</div></section></div></>};return <><div className="page-head"><div><h1>{t.schedule}</h1><p>{t.subtitle}</p></div><button className="primary" onClick={()=>setCourseForm(true)}><Plus/>{t.addCourse}</button></div><div className="week-board entity-card">{dayKeys.map((d,i)=><div className={`day-column ${weekday===i+1?"today":""}`} key={d}><header><span>{t[d]}</span><b>{i+1}</b></header><div>{data.courses.flatMap((c:any)=>c.schedule.filter((s:any)=>s.weekday===i+1).map((s:any)=><button className="class-block" style={{borderColor:c.color}} key={s.id} onClick={()=>setSelectedCourse(c.id)}><i style={{background:c.color}}/><strong>{c.name}</strong><span>{s.startTime}–{s.endTime}</span><small>{s.room}</small></button>))}</div></div>)}</div><div className="mobile-agenda">{dayKeys.map((d,i)=><section key={d}><h3>{t[d]}</h3>{data.courses.flatMap((c:any)=>c.schedule.filter((s:any)=>s.weekday===i+1).map((s:any)=><button className="agenda-row entity-card" key={s.id} onClick={()=>setSelectedCourse(c.id)}><i style={{background:c.color}}/><span>{s.startTime}</span><div><strong>{c.name}</strong><small>{s.room}</small></div><ChevronRight/></button>))}</section>)}</div></>}
function TasksView({t,data,courseMap,filter,setFilter,toggle,setFocus,setTaskForm,setData}:any){const tasks=data.tasks.filter((x:any)=>filter==="all"||(filter==="completed"?x.completed:filter==="incomplete"?!x.completed:x.type===filter));return <><div className="page-head"><div><h1>{t.tasks}</h1><p>{tasks.length} {t[filter]||t.tasks}</p></div><button className="primary" onClick={()=>setTaskForm(true)}><Plus/>{t.addTask}</button></div><div className="filter-bar entity-card">{["all","incomplete","completed",...typeKeys].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{t[x]}</button>)}</div><div className="deadline-list">{tasks.map((x:any)=><div className="task-wrap" key={x.id}><TaskRow task={x} course={courseMap[x.courseId]} t={t} toggle={toggle} setFocus={setFocus}/><button className="delete" onClick={()=>setData((d:AppData)=>({...d,tasks:d.tasks.filter(y=>y.id!==x.id)}))}><Trash2/></button></div>)}</div></>}
function StatsView({t,data,courseMap,completion}:any){const focus=data.focusSessions.reduce((a:number,b:any)=>a+b.durationMinutes,0);const types=typeKeys.map(k=>({k,n:data.tasks.filter((x:any)=>x.type===k).length}));return <><div className="page-head"><div><h1>{t.stats}</h1><p>{t.subtitle}</p></div></div><div className="stats-layout"><section className="entity-card stat-large"><span>{t.completion}</span><strong>{completion}%</strong><div className="bar"><i style={{width:`${completion}%`}}/></div></section><Metric label={t.focusTime} value={focus} icon={Timer}/><Metric label={t.streak} value={3} icon={RotateCcw}/><section className="entity-card chart-card"><SectionTitle title={t.distribution}/><div className="type-bars">{types.map((x:any)=><div key={x.k}><span>{t[x.k]}</span><i><b style={{width:`${data.tasks.length?x.n/data.tasks.length*100:0}%`}}/></i><strong>{x.n}</strong></div>)}</div></section><section className="entity-card chart-card"><SectionTitle title={t.course}/>{data.courses.map((c:any)=>{const a=data.tasks.filter((x:any)=>x.courseId===c.id);const r=a.length?Math.round(a.filter((x:any)=>x.completed).length/a.length*100):0;return <div className="course-stat" key={c.id}><i style={{background:c.color}}/><span>{c.name}</span><div className="bar"><b style={{width:`${r}%`,background:c.color}}/></div><strong>{r}%</strong></div>})}</section></div></>}
function Empty({t}:{t:any}){return <div className="empty-small">{t.empty}</div>}
function ModalShell({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-layer"><button className="modal-backdrop" onClick={close} aria-label="Close"/><section className="drawer entity-card" role="dialog" aria-modal="true"><header><h2>{title}</h2><button onClick={close}><X/></button></header>{children}</section></div>}
function TaskDrawer({t,courses,addTask,close,defaultCourse}:{t:any;courses:Course[];addTask:any;close:()=>void;defaultCourse?:string}){return <ModalShell title={t.addTask} close={close}><form className="form-grid" onSubmit={addTask}><label className="wide"><span>{t.title}</span><input name="title" required autoFocus/></label><label><span>{t.course}</span><select name="course" defaultValue={defaultCourse||""}><option value="">—</option>{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label><span>{t.type}</span><select name="type">{typeKeys.map(x=><option value={x} key={x}>{t[x]}</option>)}</select></label><label><span>{t.due}</span><input type="datetime-local" name="due"/></label><label><span>{t.priority}</span><select name="priority"><option value="high">{t.high}</option><option value="medium">{t.medium}</option><option value="low">{t.low}</option></select></label><label><span>{t.tags}</span><input name="tags" placeholder="lab, reading"/></label><label className="wide"><span>{t.notes}</span><textarea name="notes"/></label><div className="form-actions wide"><button type="button" onClick={close}>{t.cancel}</button><button className="primary">{t.save}</button></div></form></ModalShell>}
function CourseDrawer({t,addCourse,close}:{t:any;addCourse:any;close:()=>void}){return <ModalShell title={t.addCourse} close={close}><form className="form-grid" onSubmit={addCourse}><label><span>{t.title}</span><input name="name" required autoFocus/></label><label><span>{t.teacher}</span><input name="teacher"/></label><label><span>{t.room}</span><input name="room"/></label><label><span>{t.credits}</span><input name="credits" type="number" min="0" defaultValue="2"/></label><label><span>{t.monday}</span><select name="weekday">{dayKeys.map((x,i)=><option value={i+1} key={x}>{t[x]}</option>)}</select></label><label><span>Color</span><input name="color" type="color" defaultValue="#2878e3"/></label><label><span>Start</span><input name="start" type="time" defaultValue="09:00"/></label><label><span>End</span><input name="end" type="time" defaultValue="10:30"/></label><label className="wide"><span>{t.notes}</span><textarea name="notes"/></label><div className="form-actions wide"><button type="button" onClick={close}>{t.cancel}</button><button className="primary">{t.save}</button></div></form></ModalShell>}
function SettingsPanel(p:any){const {t,theme,setTheme,locale,setLocale,setSettings,customIcon,fileRef,jsonRef,iconRef,exportCsv,exportJson,importCsv,importJson,updateIcon}=p;return <ModalShell title={t.settings} close={()=>setSettings(false)}><div className="settings-content"><span>{t.appearance}</span><div className="choice-row">{(["light","dark","system"] as Theme[]).map((x,i)=>{const I=[Sun,Moon,Monitor][i];return <button className={theme===x?"active":""} onClick={()=>setTheme(x)} key={x}><I/>{t[x]}</button>})}</div><span>{t.language}</span><div className="choice-row">{(["zh","ja","en"] as Locale[]).map(x=><button className={locale===x?"active":""} onClick={()=>setLocale(x)} key={x}>{x==="zh"?"中文":x==="ja"?"日本語":"English"}</button>)}</div><span>{t.data}</span><div className="settings-actions"><button onClick={()=>fileRef.current?.click()}><Upload/>{t.importCsv}</button><button onClick={exportCsv}><Download/>{t.exportCsv}</button><button onClick={()=>jsonRef.current?.click()}><FileJson/>{t.restore}</button><button onClick={exportJson}><Download/>{t.backup}</button><button onClick={()=>iconRef.current?.click()}><div className="tiny-icon">{customIcon?<img src={customIcon}/>:<GraduationCap/>}</div>{t.icon}</button></div><input hidden ref={fileRef} type="file" accept=".csv" onChange={importCsv}/><input hidden ref={jsonRef} type="file" accept=".json" onChange={importJson}/><input hidden ref={iconRef} type="file" accept="image/*" onChange={updateIcon}/></div></ModalShell>}
